### PR TITLE
Replace RU and BY flags with proper ones.

### PR DESCRIPTION
**Pull request by alexey-medvedchikov**
So that people would know that they aren't alone and annoy pro-war shitheads.

https://en.wikipedia.org/wiki/White-blue-white_flag
https://en.wikipedia.org/wiki/White-red-white_flag

### CODE REVIEW

**Comment by fedya** [comment]
Cuckold vibes, bro.

**Comment by alexey-medvedchikov** [comment]
@fedya Sorry, I didn't get it.
Anyway, I don't like having PRs hanging and it is extremely easy to change the flag locally, so closing.

**Comment by fedya** [comment]
yes, you mmmmaxiumum cuck, bro, salo uronili

**Comment by zen-tools** [comment]
A message from Russian Nazi Fedya (Alexander Stefanov) was deleted. The thread is locked

**Pull request closed without merging**
